name: kubernetes deplomet
on: [push]
jobs:
  build-frontend:
    runs-on: ubuntu-latest
    container: node:latest
    steps:
        - run: |
            cd frondend &&
            npm install &&
            npm run build &&
            ls-la
