name: kubernetes deployment

on: 
  push:
    branches:
      - '*'

jobs:
  build-frontend:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
      - run: |
          cd frontend &&
          npm install &&
          npm run build &&
          ls -la
      - uses: actions/upload-artifact@master
        with:
          name: frontend-artifact
          path: frontend/dist/frontend/browser

  deploy-frontend:
    needs: [build-frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: frontend-artifact
          path: frontend/dist/frontend/browser
      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'eu-central-1'
          SOURCE_DIR: 'frontend/dist/frontend/browser'

  build-image:
    needs: [build-frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Login_to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: backend/
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/example-k8s-backend:${{ github.sha }}

  deploy-backend:
    needs: [build-image]
    runs-on: ubuntu-latest
    steps:
      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install ansible -y
      - name: Clone Ansible repository
        run: git clone https://github.com/ansible/ansible.git
      - name: Run Ansible playbook
        run: |
          cd ansible
          ansible-playbook -i hosts.ini deploy_backend.yml --private-key=$PRIVATE_KEY_PATH
