name: kubernetes deployment
on: 
  push:
    branches:
      - '*'
jobs:
  build-frontend:
    runs-on: ubuntu-latest  
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
      - run: |
          cd frontend &&
          npm install &&
          npm run build &&
          ls -la
      - name: Upload to S3
        uses: actions/upload-artifact@master
        with:
          name: frontend-artifact
          path: frontend/dist/frontend/browser

  deploy-frontend:
    needs: build-frontend
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@master
        with:
          name: frontend-artifact
          path: frontend/dist/frontend/browser
      - name: Deploy to S3
        run: |
          aws --version
          cd frontend/dist/frontend/browser
          ls -la
          aws s3 cp . s3://$AWS_S3_BUCKET/ --recursive

  build-image:
    needs: build-frontend
    runs-on: ubuntu-latest
    steps:
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend:$IMAGE_TAG

  deploy-backend:
    needs: build-image
    runs-on: ubuntu-latest
    steps:
      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install ansible
      - name: Deploy backend to EC2
        run: |
          ansible --version
          ansible-playbook -i hosts.ini deploy_backend.yml --private-key=./temp_key.pem
          rm -f ./temp_key.pem
          



